### ISSUE TITLE
Add issue template to repository for bug reports

### ISSUE THREAD

**Issue by nicolasbock** [Temperate-Designs/sunflower-dash#9]
Add a file to `.github/ISSUE_TEMPLATE/bug_report.md`,

**Comment by nicolasbock** [comment]
Add a file to `.github/ISSUE_TEMPLATE/bug_report.md`

**Comment by AnirbanBall** [comment]
I can work on that please assign on me

**Comment by nicolasbock** [comment]
Go ahead :)

Please don't forget to add
```
Closes: Temperate-Designs/sunflower-dash#9
```

To your commit message.

**Comment by AnirbanBall** [comment]
Sure Thanks for assigning me 😊
